version: '3.9'
services:

#***************************************************************
# OpenClimate backend API
#***************************************************************

  hub-api:
    image: hub-api:version1.0
    build: .
    restart: unless-stopped
    ports:
     - "3100:3100"
    environment: 
      - NODE_ENV=${NODE_ENV}
      - CONTROLLERPORT=${CONTROLLERPORT}
      - AGENTADDRESS=${AGENTADDRESS}
      - WEB_ROOT=${WEB_ROOT}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      # - SCHEMA_CLIMATE_ORGANIZATION=XSYhjGtcha6oCAzaVg34df:2:Climate_Organization:1.1
      - SCHEMA_VERIFIED_EMPLOYEE=${SCHEMA_VERIFIED_EMPLOYEE}
      - SCHEMA_VALIDATED_EMAIL=${SCHEMA_VALIDATED_EMAIL}
      - POSGRES_ADDRESS=${POSGRES_ADDRESS}
      - POSGRES_DB=${POSGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSGRES_PASSWORD=${POSGRES_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
          limits:
              cpus: '4'
              memory: 4G