version: "3.9"
services:
  traction-api:
    build:
      context: ./traction/services/traction
      dockerfile: Dockerfile
    depends_on:
      endorser-agent:
        condition: service_started
      traction-agent:
        condition: service_started
      traction-db:
        condition: service_healthy
    entrypoint: bash -c "alembic upgrade head && uvicorn api.main:app --reload --host 0.0.0.0 --port 5000 --log-level info"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${TRACTION_PSQL_DB}
      - TRACTION_DB_ADMIN=${TRACTION_PSQL_ADMIN}
      - TRACTION_DB_ADMIN_PWD=${TRACTION_PSQL_ADMIN_PWD}
      - TRACTION_DB_USER=${TRACTION_PSQL_USER}
      - TRACTION_DB_USER_PWD=${TRACTION_PSQL_USER_PWD}
      - TRACTION_API_ADMIN_USER=${TRACTION_API_ADMIN_USER}
      - TRACTION_API_ADMIN_KEY=${TRACTION_API_ADMIN_KEY}
      - ACAPY_ADMIN_URL=${ACAPY_ADMIN_URL}
      - ACAPY_ADMIN_URL_API_KEY=${ACAPY_ADMIN_URL_API_KEY}
      - ENVIRONMENT=production
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - TRACTION_HOST_URL=${TRACTION_HOST_URL}
      - TRACTION_WEBHOOK_URL=${TRACTION_WEBHOOK_URL}
      - TRACTION_TENANT_WEBHOOK_URL=${TRACTION_TENANT_WEBHOOK_URL}
      - ACAPY_WEBHOOK_URL_API_KEY=${ACAPY_WEBHOOK_URL_API_KEY}
      - ACAPY_ENDORSER_PUBLIC_DID=${ACAPY_ENDORSER_PUBLIC_DID}
      - ENDORSER_CONNECTION_ALIAS=${ENDORSER_CONNECTION_ALIAS}
      - ACAPY_GENESIS_URL=${ACAPY_GENESIS_URL}
      - DEFAULT_RETRY_ATTEMPTS=${DEFAULT_RETRY_ATTEMPTS:-10}
      - DEFAULT_PAUSE_BETWEEN_ATTEMPTS=${DEFAULT_PAUSE_BETWEEN_ATTEMPTS:-2}
    ports:
      - ${TRACTION_SERVICE_PORT}:5000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./traction/services/traction:/app:rw
    networks:
      - openclimate_oc-network

  traction-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3
    depends_on:
      endorser-agent:
        condition: service_started
      traction-db:
        condition: service_healthy
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5;
        aca-py start \
        --auto-provision
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_HTTP_PORT} \
        --webhook-url '${TRACTION_WEBHOOK_URL}' \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --wallet-name traction-wallet  \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --emit-new-didcomm-prefix \
        --label '${AGENT_NAME}' \
        --jwt-secret '${JWT_SECRET}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        ${ACAPY_TAILS_BASE_URL} \
        ${ACAPY_TAILS_UPLOAD_URL} \
        --endorser-protocol-role author \
        --endorser-public-did ${ACAPY_ENDORSER_PUBLIC_DID} \
        --endorser-alias ${ENDORSER_CONNECTION_ALIAS} \
        --auto-request-endorsement \
        --auto-write-transactions \
        --auto-create-revocation-transactions \
        ",
      ]
    volumes:
      - "./traction/scripts/acapy-static-args.yml:/home/indy/acapy-static-args.yml"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - openclimate_oc-network

  traction-db:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - traction-wallet:/var/lib/postgresql/data
      - ./traction/scripts/db_init.sql:/docker-entrypoint-initdb.d/1-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openclimate_oc-network

  endorser-api:
    build:
      context: ./traction/services/endorser
      dockerfile: Dockerfile
    depends_on:
      endorser-agent:
        condition: service_started
      endorser-db:
        condition: service_healthy
    environment:
      - POSTGRESQL_HOST=${ENDORSER_POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${ENDORSER_POSTGRESQL_PORT}
      - POSTGRESQL_DB=${ENDORSER_PSQL_DB}
      - ENDORSER_DB_ADMIN=${ENDORSER_PSQL_ADMIN}
      - ENDORSER_DB_ADMIN_PWD=${ENDORSER_PSQL_ADMIN_PWD}
      - ENDORSER_DB_USER=${ENDORSER_PSQL_USER}
      - ENDORSER_DB_USER_PWD=${ENDORSER_PSQL_USER_PWD}
      - ENDORSER_API_ADMIN_USER=${ENDORSER_API_ADMIN_USER}
      - ENDORSER_API_ADMIN_KEY=${ENDORSER_API_ADMIN_KEY}
      - ACAPY_ADMIN_URL=${ENDORSER_ACAPY_ADMIN_URL}
      - ACAPY_ADMIN_URL_API_KEY=${ENDORSER_ACAPY_ADMIN_URL_API_KEY}
      - ENVIRONMENT=production
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - TRACTION_WEBHOOK_URL=${ENDORSER_WEBHOOK_URL}
      - ACAPY_WEBHOOK_URL_API_KEY=${ENDORSER_ACAPY_WEBHOOK_URL_API_KEY}
    ports:
      - ${ENDORSER_SERVICE_PORT}:5000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./traction/services/endorser:/app:rw
    networks:
      - openclimate_oc-network

  endorser-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3
    depends_on:
      endorser-db:
        condition: service_healthy
    ports:
      - ${ACAPY_ENDORSER_ADMIN_PORT}:${ACAPY_ENDORSER_ADMIN_PORT}
      - ${ACAPY_ENDORSER_HTTP_PORT}:${ACAPY_ENDORSER_HTTP_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5;
        aca-py start \
        --auto-provision
        --arg-file endorser-acapy-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_ENDORSER_HTTP_PORT} \
        --webhook-url '${ENDORSER_WEBHOOK_URL}' \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY_ENDORSER_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${ENDORSER_POSTGRESQL_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${ENDORSER_POSTGRESQL_USER}\",\"password\":\"${ENDORSER_POSTGRESQL_PASSWORD}\",\"admin_account\":\"${ENDORSER_POSTGRESQL_USER}\",\"admin_password\":\"${ENDORSER_POSTGRESQL_PASSWORD}\"}' \
        --wallet-name endorser-wallet  \
        --seed '${ACAPY_ENDORSER_SEED}' \
        --admin '0.0.0.0' ${ACAPY_ENDORSER_ADMIN_PORT} \
        --label '${ENDORSER_AGENT_NAME}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        --endorser-protocol-role endorser \
        --auto-endorse-transactions \
        ",
      ]
    volumes:
      - "./traction/scripts/endorser-acapy-args.yml:/home/indy/endorser-acapy-args.yml"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - openclimate_oc-network

  endorser-db:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=${ENDORSER_POSTGRESQL_PASSWORD}
    ports:
      - ${ENDORSER_POSTGRESQL_PORT}:5432
    volumes:
      - endorser-wallet:/var/lib/postgresql/data
      - ./traction/scripts/db_init.sql:/docker-entrypoint-initdb.d/1-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openclimate_oc-network

volumes:
  traction-wallet:
  endorser-wallet:

networks:
  openclimate_oc-network:
    external: true