version: '3.9'
services:

#***************************************************************
# OpenClimate UI
#***************************************************************

  hub-ui-prod:
    container_name: openclimate-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1337:80'
    environment: 
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_CONTROLLER=${REACT_APP_CONTROLLER}
      - BROWSER=${BROWSER}
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
          limits:
              cpus: '4'
              memory: 4G

  # hub-ui:
  #   image: node:12-stretch
  #   hostname: hub-ui
  #   restart: unless-stopped
  #   user: root # To write to ui folder, we need write permissions. node user does not have this.
  #   tty: true # keep react from stopping development server
  #   working_dir: /home/node/app
  #   environment: 
  #     - NODE_ENV=${NODE_ENV}
  #     - REACT_APP_CONTROLLER=${REACT_APP_CONTROLLER}
  #     - BROWSER=${BROWSER}
  #   volumes:
  #     - ./:/home/node/app:rw
  #   expose:
  #     - "3000"
  #   ports:
  #     - '3000:3000'
  #   command: >
  #     sh -c "npm install && npm start"
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   deploy:
  #     resources:
  #         limits:
  #             cpus: '4'
  #             memory: 4G