export default interface ITransfer {
    credential_category: string,
    credential_type?: string,
    credential_schema_id?: string,
    credential_issuer?: string,
    credential_issue_date?: number,
    organization_name?: string,
    organization_category?: string,
    organization_type?: string,
    organization_credential_id?: string,
    facility_name?: string,
    facility_jurisdiction?: string,
    facility_location?: string,
    facility_sector_ipcc_category?: string,
    facility_sector_ipcc_activity?: string,
    facility_sector_naics?: string,
    transfer_date?: Date,
    transfer_goods?: string,
    transfer_quantity?: number,
    transfer_quantity_unit?: string,
    transfer_carbon_intensity?: number,
    transfer_carbon_intensity_credential_id?: string,
    transfer_carbon_associated?: number,
    transfer_receiver_organization?: string,
    transfer_receiver_jurisdiction?: string,
    signature_name?: string
}