apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclimate-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: openclimate-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openclimate-ui-service
            port:
              number: 80
