apiVersion: batch/v1
kind: Job
metadata:
  generateName: openclimate-migrations-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: openclimate-migrations
        image: public.ecr.aws/openearthfoundation/openclimate-api:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: openclimate-db-configmap
        env:
        - name: NODE_ENV
          value: development
        command: ["npm",  "run", "migrate_up_all"]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
