apiVersion: batch/v1
kind: Job
metadata:
  generateName: openclimate-to-elasticsearch-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
      - name: openclimate-to-elasticsearch
        image: public.ecr.aws/openearthfoundation/openclimate-to-elasticsearch:latest
        env:
          - name: OPENCLIMATE_DATABASE
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_DB
          - name: OPENCLIMATE_HOST
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_ADDRESS
          - name: OPENCLIMATE_USER
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSTGRES_USER
          - name: OPENCLIMATE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_PASSWORD
          - name: OPENCLIMATE_ES_NODE
            value: "http://openclimate-elasticsearch-service:9200/"
          - name: OPENCLIMATE_ES_INDEX
            value: actors
          - name: OPENCLIMATE_ES_USER
            value: "elastic"
          - name: OPENCLIMATE_ES_PASSWORD
            value: "manor claw track near buck bonus"
      restartPolicy: OnFailure
  backoffLimit: 4