# openclimate-import-zip-job.yml
# Runs a single task that imports all the processed harmonized data in the develop
# branch by downloading it from GitHub. Kind of crazy but it just might work.
# It should work on both remote and local.
apiVersion: batch/v1
kind: Job
metadata:
  generateName: openclimate-import-zip-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
      - name: openclimate-import
        image: public.ecr.aws/openearthfoundation/openclimate-import:latest
        env:
          - name: OPENCLIMATE_DATABASE
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_DB
          - name: OPENCLIMATE_HOST
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_ADDRESS
          - name: OPENCLIMATE_USER
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSTGRES_USER
          - name: OPENCLIMATE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_PASSWORD
          - name: ZIP_FILE_URL
            value: https://github.com/Open-Earth-Foundation/OpenClimate/archive/refs/heads/develop.zip
          - name: PROCESSED_DATA_DIR
            value: OpenClimate-develop/harmonize/data/processed/
      restartPolicy: OnFailure
  backoffLimit: 4