apiVersion: batch/v1
kind: Job
metadata:
  generateName: openclimate-import-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      volumes:
          - name: openclimate-harmonize-data
            persistentVolumeClaim:
              claimName: openclimate-harmonize-persistentvolumeclaim
      containers:
      - name: openclimate-import
        image: public.ecr.aws/openearthfoundation/openclimate-import:latest
        env:
          - name: OPENCLIMATE_DATABASE
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_DB
          - name: OPENCLIMATE_HOST
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_ADDRESS
          - name: OPENCLIMATE_USER
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSTGRES_USER
          - name: OPENCLIMATE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openclimate-db-configmap
                key: POSGRES_PASSWORD
          - name: PROCESSED_DATA_DIR
            value: /harmonize/data/processed/
        volumeMounts:
          - mountPath: "/harmonize"
            name: openclimate-harmonize-data
      restartPolicy: OnFailure
  backoffLimit: 4