apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclimate-api-deployment
  labels:
    app: openclimate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openclimate-api
  template:
    metadata:
      labels:
        app: openclimate-api
    spec:
      containers:
      - name: openclimate-api
        image: public.ecr.aws/openearthfoundation/openclimate-api:latest
        # Set to Never for local
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        env:
        - name: NODE_ENV
          value: development
        - name: CONTROLLERPORT
          value: "3100"
        - name: AGENTADDRESS
          value: http://acapy-service:8150
        - name: WEB_ROOT
          value: https://localhost
        - name: JWT_SECRET
          value: ZBVgToVv72zffZE2ksUYNAhYmNCXwgKp
        - name: SESSION_SECRET
          value: aZj6iXNkrtmLrAT0HsTrp7dRR7r4U7P0
        - name: SCHEMA_VERIFIED_EMPLOYEE
          value: RSaZ64jxn2NbpH8MgBdy4C:2:Verified_Employee:1.0
        - name: POSGRES_ADDRESS
          value: dev-db-aurora.cluster-c5ipsfxjhb0m.us-east-1.rds.amazonaws.com
        - name: POSGRES_DB
          value: development
        - name: POSTGRES_USER
          value: development
        - name: POSGRES_PASSWORD
          value: development
        - name: ELASTIC_SEARCH_ENABLED
          value: "yes"
        - name: OPENCLIMATE_LOG_LEVEL
          value: 'debug'
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/second-controller
            port: 3100
            httpHeaders:
            - name: X-Liveness-Probe
              value: "True"
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /api/second-controller
            port: 3100
            httpHeaders:
            - name: X-Liveness-Probe
              value: "True"
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
