apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: NodePort
  selector:
    app: postgresql
  ports:
  - name: postgresql-service-port
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30543 # must be in range 30000-32767