apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-persistentvolumeclaim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
