apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
