apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclimate-elasticsearch-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
