apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
 
# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: app
# spec:
#   containers:
#   - name: app
#     image: centos
#     command: ["/bin/sh"]
#     args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
#     volumeMounts:
#     - name: persistent-storage
#       mountPath: /data
#   nodeSelector:
#     testing: testing2
#   volumes:
#   - name: persistent-storage
#     persistentVolumeClaim:
#       claimName: postgresql-persistentvolume