version: 0.2
env:
  variables:
    TF_VERSION: "0.10.7"
phases:
  install:
    commands:
      - pwd
      - ls
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - sed -i 's/<ACCOUNTID>/'$ACCOUNTID'/g' Dockerfile
      - sed -i 's/<REGION>/'$AWS_DEFAULT_REGION'/g' Dockerfile
      - sed -i 's/<GOOGLE_MAP_API_KEY>/'$GOOGLE_MAP_API_KEY'/g' taskdef.json
      - echo REACT_APP_CONTROLLER='https://'$REACT_APP_CONTROLLER > .env
      - cat .env
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ui .
      - echo "Version--> " `cat version.txt`
      - VERSION=`cat version.txt`
      - docker tag ui $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ui:$VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ui:$VERSION
      - sed -i 's/<VERSION>/'$VERSION'/g' taskdef.json
      - sed -i 's/<REGION>/'$AWS_DEFAULT_REGION'/g' taskdef.json
      - sed -i 's/<ACCOUNTID>/'$ACCOUNTID'/g' taskdef.json
      - sed -i 's/<REACT_APP_CONTROLLER>/'$REACT_APP_CONTROLLER'/g' taskdef.json


artifacts:
  files:
    - 'taskdef.json'
    - 'buildspec.yml'
    - 'appspec.yml'
