export const pledges = [
  {
    pledge_id: 1,
    pledge_type: 1502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2014,
    pledge_base_level: 656086,
    pledge_target: 15,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Cf the actions plan of the Energy transition scheme for New Caledonia in the transport sector.Transport GHG emissions increased.",
    region_name: "Jujuy",
  },
  {
    pledge_id: 2,
    pledge_type: 7002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2020,
    pledge_base_level: 670000,
    pledge_target: 70,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "New South Wales",
  },
  {
    pledge_id: 3,
    pledge_type: 10002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2005,
    pledge_base_level: 121446794,
    pledge_target: 100,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "Net zero emissions region-wide",
    region_name: "Queensland",
  },
  {
    pledge_id: 4,
    pledge_type: 0.10203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 1844800,
    pledge_target: 0.1,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Queensland",
  },
  {
    pledge_id: 5,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2007,
    pledge_base_level: 63401127,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In December 2020, B.C. set a near term emission target that requires greenhouse gases in B.C. to be 16% below 2007 levels by 2025. It provides a benchmark on the road to B.C.â€™s legislated emission targets for 2030, 2040 and 2050 of 40%, 60% and 80% below 2007 levels, respectively. The Province also set sectoral targets, these GHG targets for 2030 are expressed as a percentage reduction from 2007 sector emissions. Target ranges for each sector: transportation â€“ 27 to 32%; industry â€“ 38 to 43%; oil and gas â€“ 33 to 38%; and buildings and communities â€“ 59 to 64%. In additional the province will develop legislation to ensure B.C. reaches net-zero emissions by 2050.  B.C. has publicly expressed its support for achieving the long-term goals of the Paris agreement.",
    region_name: "South Australia",
  },
  {
    pledge_id: 6,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2007,
    pledge_base_level: 63401127,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In December 2020, B.C. set a near term emission target that requires greenhouse gases in B.C. to be 16% below 2007 levels by 2025. It provides a benchmark on the road to B.C.â€™s legislated emission targets for 2030, 2040 and 2050 of 40%, 60% and 80% below 2007 levels, respectively. The Province also set sectoral targets, Sectoral greenhouse gas targets for 2030 are expressed as a percentage reduction from 2007 sector emissions. Target ranges for each sector: transportation â€“ 27 to 32%; industry â€“ 38 to 43%; oil and gas â€“ 33 to 38%; and buildings and communities â€“ 59 to 64%. In additional the province will develop legislation to ensure B.C. reaches net-zero emissions by 2050.  B.C. has publicly expressed its support for achieving the long-term goals of the Paris agreement.",
    region_name: "South Australia",
  },
  {
    pledge_id: 7,
    pledge_type: 9502050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 0,
    pledge_target: 95,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "South Australia",
  },
  {
    pledge_id: 8,
    pledge_type: 2002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2010,
    pledge_base_level: 2359000,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "South Ostrobothnia has greenhouse gas emission reduction target of 20 % by 2020 compared to 2010.",
    region_name: "Victoria",
  },
  {
    pledge_id: 9,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 2021,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Victoria",
  },
  {
    pledge_id: 10,
    pledge_type: 8502050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 236190000,
    pledge_target: 85,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The CLCPA sets a long-term target of 85% reduction from 1990.  The act also revises the 1990 baseline to be developed from 20-yr GWP and include imported electricity emissions along with upstream emissions from fossil fuels consumed within the state.  This baseline will be revised in the future (by Jan 1, 2021) to be consistent with this act.  Currently the 1990 emissions reported here are based on 100-yr GWP and do not include upstream fossil fuel emissions.",
    region_name: "Victoria",
  },
  {
    pledge_id: 11,
    pledge_type: 2002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2005,
    pledge_base_level: 121446794,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Note: Victoriaâ€™s 2020 emissions reduction target is 15-20% below 2005 levels.",
    region_name: "Victoria",
  },
  {
    pledge_id: 12,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Lower Austria",
  },
  {
    pledge_id: 13,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Upper Austria",
  },
  {
    pledge_id: 14,
    pledge_type: 10002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2005,
    pledge_base_level: 25478168.65,
    pledge_target: 100,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "80% emissions reduction in 2050. The target is aligned with European Union decarbonization pathway to 2050 and the contribution to Paris Pledge.Later, an interinstitutional declaration and a draft bill forces us to climate neutrality  that forces us to be climate neutral by 2050.  Strategy and plan updates are in  development.",
    region_name: "Centre Nord",
  },
  {
    pledge_id: 15,
    pledge_type: 7502050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2001,
    pledge_base_level: 345589915,
    pledge_target: 75,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "This is a regional target for the Conference of New England governors and Eastern Canadian premiers (NEG-ECP). The NEG-ECP include the states of Connecticut, Maine, Massachusetts, New Hampshire, Rhode and Vermont as well as the provinces of New Brunswick, Nova Scotia, Newfoundland and Labrador, Prince Edward Island and QuÃ©bec. The governors and premiers meet each year to review progress and to adopt new initiatives to reduce GHG emissions through resolutions.",
    region_name: "Acre",
  },
  {
    pledge_id: 16,
    pledge_type: 8002035,
    pledge_target_year: 2035,
    pledge_baseline_year: 2005,
    pledge_base_level: 3099,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Kymenlaakso aims to be carbon neutral by 2035. Carbon neutrality will be achieved by cutting emissions by 80% and the remaining 20% will be offset and/or covered by increased carbon sinks.",
    region_name: "Bahia",
  },
  {
    pledge_id: 17,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2005,
    pledge_base_level: 86500000,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Reduction of region-wide CO2e emissions by 80% by 2050 based on 2005 levels.All emissions within the regional territory except point source emissions included in the EU-ETS (Emission TradingSystem of the European Union), plus indirect emissions from regional power consumption. The target applies to thesources in sectors a+c+d+e+f+g defined in Q 3.11 d.",
    region_name: "Ceara",
  },
  {
    pledge_id: 18,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2001,
    pledge_base_level: 51357263,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target established in Global Warming Solutions Act, 2008. Decarbonization pathway modeled for Governor's Council on Climate Change, 2018: https://www.ct.gov/deep/lib/deep/climatechange/publications/building_a_low_carbon_future_for_ct_gc3_recommendations.pdf (see p. 14).",
    region_name: "Espirito Santo",
  },
  {
    pledge_id: 19,
    pledge_type: 1402030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 1963608,
    pledge_target: 14,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Para lograr la meta se han planteado estrategias y lÃ­neas de acciÃ³n para reducir las emisiones de GEI asociadas a la electricidad; y potenciar el uso de modos de transporte mÃ¡s sustentables, asÃ­ como la mejora de la eficiencia del parque mÃ³vilactual.",
    region_name: "Federal District",
  },
  {
    pledge_id: 20,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 56128148.64,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Goias",
  },
  {
    pledge_id: 21,
    pledge_type: 3002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2010,
    pledge_base_level: 46756.79,
    pledge_target: 30,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The State Program of Action on Climate Change, 2018, will contain Climate Agenda, which established mitigation and adaptation actions, that may be carried out by the government agencies that make up the Inter-Secretariat Commission on Climate Change, as it marks the State Law on Climate Change. This Agenda has an execution period of 2017-2023 as established in the State Plan Development.",
    region_name: "Mato Grosso",
  },
  {
    pledge_id: 22,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 10130190,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Se ha propuesto un desarrollo bajo en emisiones de gases de efecto invernadero (GEI), mediante la conservaciÃ³n del potencial sumidero de carbono de las Ã¡reas naturales protegidas, estableciendo una hoja de ruta al 2030 del Estado de YucatÃ¡n para la reducciÃ³n de las emisiones de GEI, en un 40% al 2030 de las emisiones de GEI. respecto al aÃ±o base 2005, a travÃ©s de estrategias y lÃ­neas de acciÃ³n de los sectores emisores de GEI.",
    region_name: "Mato Grosso do sul",
  },
  {
    pledge_id: 23,
    pledge_type: 1002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 1990,
    pledge_base_level: 45540974,
    pledge_target: 10,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target established in Global Warming Solutions Act, 2008.  Target is based on annual emissions as of Jan. 1, 2020, hence emissions in calendar year 2019.",
    region_name: "Minas Gerais",
  },
  {
    pledge_id: 24,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Para",
  },
  {
    pledge_id: 25,
    pledge_type: 10002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 85709000,
    pledge_target: 100,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "QuÃ©bec has announced that it will adopt a net zero GHG emissions target for the year 2050. The details of this target are yet to come. GHGs covered by the target include CO2, CH4, N2O, SF6, NF3, HFCs and PFCs.",
    region_name: "Parana",
  },
  {
    pledge_id: 26,
    pledge_type: 6002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 37453000,
    pledge_target: 60,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Legislative target under the Climate Change and Greenhouse Emission Reduction Act 2007",
    region_name: "Pernambuco",
  },
  {
    pledge_id: 27,
    pledge_type: 3502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 328109693,
    pledge_target: 35,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "This is a regional target for the Conference of New England governors and Eastern Canadian premiers (NEG-ECP). The NEG-ECP include the states of Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island and Vermont as well as the provinces of New Brunswick, Nova Scotia, Newfoundland and Labrador, Prince Edward Island and QuÃ©bec. The governors and premiers meet each year to review progress and to adopt new initiatives to reduce GHG emissions through resolutions.",
    region_name: "Rio de Janeiro (State)",
  },
  {
    pledge_id: 28,
    pledge_type: 2602030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 4084620,
    pledge_target: 26,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Rio de Janeiro (State)",
  },
  {
    pledge_id: 29,
    pledge_type: 7002040,
    pledge_target_year: 2040,
    pledge_baseline_year: 1990,
    pledge_base_level: 90498300,
    pledge_target: 70,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "See https://www.governor.wa.gov/issues/issues/energy-environment/deep-decarbonization",
    region_name: "Rio de Janeiro (State)",
  },
  {
    pledge_id: 30,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Rio de Janeiro (State)",
  },
  {
    pledge_id: 31,
    pledge_type: 8002040,
    pledge_target_year: 2040,
    pledge_baseline_year: 1990,
    pledge_base_level: 0,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target for 2040: 70-80 % reduction ( action is geared to maximum emission reduction) Taget is fixed in  the bill of an Thuringian Climate Act",
    region_name: "Rio Grande do Norte",
  },
  {
    pledge_id: 32,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Rio Grande do Sul",
  },
  {
    pledge_id: 33,
    pledge_type: 3.30203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2011,
    pledge_base_level: 16108.8,
    pledge_target: 3.3,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The development of Integrated Waste Management Facility (TPST) and Reduce, Reuse, Recycle (3R) waste management policy.",
    region_name: "RondÃ´nia",
  },
  {
    pledge_id: 34,
    pledge_type: 202030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 588730,
    pledge_target: 2,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Roraima",
  },
  {
    pledge_id: 35,
    pledge_type: 9502050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 33800000,
    pledge_target: 95,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target for 2050: 80-95 % reduction ( action is geared to maximum emission reduction) Taget is fixed in  the bill of an Thuringian Climate Act;From 1990 to 2014 the emissions were already reduced by around 56 % (most of the reduction took place in the early 1990s)",
    region_name: "SÃ£o Paulo State",
  },
  {
    pledge_id: 36,
    pledge_type: 4502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 90498300,
    pledge_target: 45,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "See https://www.governor.wa.gov/issues/issues/energy-environment/deep-decarbonization",
    region_name: "Santa Catarina",
  },
  {
    pledge_id: 37,
    pledge_type: 1002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2011,
    pledge_base_level: 4700000,
    pledge_target: 10,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target gases: CO2, CH4, N20, HFCs, PFCs, SF6, NF3Target sectors: Energy, Transport, Industry, Agriculture, WasteShort target summary: Reduce region-wide GHG emissions by 10% by 2020 based on 2011 levels.Please detail and comment on any progress to reach targetThe regional scheme takes into account all sectors but actions are focused on GHG emissions linked to energyconsumption and transport1. Actions to decrease the energy consumption :-The Eco-solidarity scheme : low-income families received joint grants from The Regional Council and EDF (FrenchElectricity Center) to finance the installationof a solar heat water- The Energy Solidarity Network aims to educate, support and assist families in rationalising their electricityconsumption. Information campaigns and personaladvice is made by 30 Energy Ambassadors (trained by The Regional Council ).2. Development of alternative low carbon transport : hybrid and electric vehicles/Bicycle",
    region_name: "Sergipe",
  },
  {
    pledge_id: 38,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2020,
    pledge_base_level: 52472569,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Acciones de adaptaciÃ³n al cambio climÃ¡tico se han venido trabajando desde 2014 a la fecha, a travÃ©s de Agendas municipales y sectoriales dentro del Estado, acciones concretas en eficiencia energÃ©tica, manejo y disposiciÃ³n de RSU efectiva, etc.Fuente: https://www.gob.mx/cms/uploads/attachment/file/418382/31_ProAire_Veracruz.pdf",
    region_name: "Tocantins",
  },
  {
    pledge_id: 39,
    pledge_type: 5.20203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 330300,
    pledge_target: 5.2,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Para lograr esta meta se impulsarÃ¡  la gestiÃ³n integral y sustentable de los residuos sÃ³lidos urbanos y de manejo especial.",
    region_name: "Tocantins",
  },
  {
    pledge_id: 40,
    pledge_type: 4502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2001,
    pledge_base_level: 51357263,
    pledge_target: 45,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target established in Public Act 18-82, An Act Concerning Climate Change Planning and Resiliency. Decarbonization pathway modeled for Governor's Council on Climate Change in 2018: https://www.ct.gov/deep/lib/deep/climatechange/publications/building_a_low_carbon_future_for_ct_gc3_recommendations.pdf.",
    region_name: "Tocantins",
  },
  {
    pledge_id: 41,
    pledge_type: 5002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 11213000,
    pledge_target: 50,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "GHGs covered by the target include CO2, CH4, N2O, SF6, NF3, HFCs and PFCs.",
    region_name: "Tocantins",
  },
  {
    pledge_id: 42,
    pledge_type: 2602030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 67364706,
    pledge_target: 26,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "El objetivo se expresa en emisiones totales (ETS y No ETS).",
    region_name: "Tocantins",
  },
  {
    pledge_id: 43,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "British Columbia",
  },
  {
    pledge_id: 44,
    pledge_type: 37.50203,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 85709000,
    pledge_target: 37.5,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "QuÃ©becâ€™s GHG emissions reduction target for 2030 is a reduction of 37.5% compared to 1990 levels. Since QuÃ©becâ€™s GHG emissions were approximately of 86 Mt CO2 eq in 1990, this translates to a target of approximately 54 Mt CO2 eq in 2030. GHGs covered by the target include CO2, CH4, N2O, SF6, NF3, HFCs and PFCs.",
    region_name: "British Columbia",
  },
  {
    pledge_id: 45,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "British Columbia",
  },
  {
    pledge_id: 46,
    pledge_type: 8302050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 19500000,
    pledge_target: 83,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Prince Edward Island",
  },
  {
    pledge_id: 47,
    pledge_type: 0.980203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2011,
    pledge_base_level: 129282440,
    pledge_target: 0.98,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The development of renewable energy facility and eco-friendly energy policy.",
    region_name: "Prince Edward Island",
  },
  {
    pledge_id: 48,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 86500000,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Reduction of region-wide CO2e emissions by 40% by 2030 based on 2005 levels.All emissions within the regional territory except point source emissions included in the EU-ETS (Emission TradingSystem of the European Union), plus indirect emissions from regional power consumption. The target applies to thesources in sectors a+c+d+e+f+g defined in Q 3.11 d.",
    region_name: "Quebec",
  },
  {
    pledge_id: 49,
    pledge_type: 1002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 1990,
    pledge_base_level: 56128148.64,
    pledge_target: 10,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Quebec",
  },
  {
    pledge_id: 50,
    pledge_type: 2020,
    pledge_target_year: 2020,
    pledge_baseline_year: 1990,
    pledge_base_level: 90498300,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "See https://www.governor.wa.gov/issues/issues/energy-environment/deep-decarbonizationThe Washington State target for 2020 is to reduce overall emissions of greenhouse gases in the state to 1990 levels.",
    region_name: "Quebec",
  },
  {
    pledge_id: 51,
    pledge_type: 5002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 121446794,
    pledge_target: 50,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Note: Victoriaâ€™s 2030 emissions reduction target is 45-50% below 2005 levels.",
    region_name: "Quebec",
  },
  {
    pledge_id: 52,
    pledge_type: 8.690203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2011,
    pledge_base_level: 705236092.6,
    pledge_target: 8.69,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "West Kalimantan has set the 60% emissions reduction target by 2020 in the LULUCF sector to 2030.",
    region_name: "Quebec",
  },
  {
    pledge_id: 53,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Com vistas a isso, o Tocantins irÃ¡ reduzir em 40% os Ã­ndices anuais de desmatamento do bioma Cerrado, atÃ© 2020, em relaÃ§Ã£o Ã  mÃ©dia verificada entre 1999 e 2008, em consonÃ¢ncia com as metas e prazos do Plano de AÃ§Ã£o para PrevenÃ§Ã£o e Controle do Desmatamento e das Queimadas no Cerrado (PPCerrado) e zerar o desmatamento ilegal no Estado atÃ© 2050, atravÃ©s do PSA, de atividades produtivas sustentÃ¡veis, monitoramento, fiscalizaÃ§Ã£o, ordenamento territorial e educaÃ§Ã£o ambiental.",
    region_name: "Quebec",
  },
  {
    pledge_id: 54,
    pledge_type: 6002040,
    pledge_target_year: 2040,
    pledge_baseline_year: 2007,
    pledge_base_level: 63401127,
    pledge_target: 60,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In December 2020, B.C. set a near term emission target that requires greenhouse gases in B.C. to be 16% below 2007 levels by 2025. It provides a benchmark on the road to B.C.â€™s legislated emission targets for 2030, 2040 and 2050 of 40%, 60% and 80% below 2007 levels, respectively. The Province also set sectoral targets, Sectoral GHG targets for 2030 are expressed as a percentage reduction from 2007 sector emissions. Target ranges for each sector: transportation â€“ 27 to 32%; industry â€“ 38 to 43%; oil and gas â€“ 33 to 38%; and buildings and communities â€“ 59 to 64%. In additional the province will develop legislation to ensure B.C. reaches net-zero emissions by 2050.   B.C. has publicly expressed its support for achieving the long-term goals of the Paris agreement.",
    region_name: "Sud-Comoe",
  },
  {
    pledge_id: 55,
    pledge_type: 1002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2014,
    pledge_base_level: 2964383,
    pledge_target: 10,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Cf the actions plan of the Energy transition scheme for New Caledonia in the mining and metallurgy  sectorMining and metallurgy GHG emissions increased.",
    region_name: "CaquetÃ¡",
  },
  {
    pledge_id: 56,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 431000000,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The State's targets are focused on reducing GHG emissions from industrial and fossil fuel sources.  The pathway to achieve the 2030 target was modelled using E3's PATHWAYS model and is detailed in CARB's 2017 Climate Change Scoping Plan Update at: https://ww2.arb.ca.gov/our-work/programs/ab-32-climate-change-scoping-plan/2017-scoping-plan-documents.",
    region_name: "NariÃ±o",
  },
  {
    pledge_id: 57,
    pledge_type: 2502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 1360080,
    pledge_target: 25,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Para lograr la meta se  proponen diversas lineas de acciÃ³n para mantener las superficies naturales y forestales del estado de YucatÃ¡n, frenando su degradaciÃ³n.",
    region_name: "RAP Pacifico",
  },
  {
    pledge_id: 58,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 27155,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Thuringia",
  },
  {
    pledge_id: 59,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 697681,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Thuringia",
  },
  {
    pledge_id: 60,
    pledge_type: 3602030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 12954000,
    pledge_target: 36,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "This target is  based on NON-ETS emissions (base year 2005: 12,954,000; target year 2030: 8,291,000; target -36%) and ETS-emissions (base year 2005: 9,154,000; target year 2030: 5,218,000; target -43%)total emissions including ETS (2005: 22,108,000; 2030: 13,508,000; -39%)",
    region_name: "Thuringia",
  },
  {
    pledge_id: 61,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 41590448,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Catalonia is committed to reducing its GHG emissions in the proportional part that corresponds to the general objective agreed by the EU. For this reason, the targets will be reviewed when the European Union updates and modifies its emission reduction targets. So that, we are currently in the process of reviewing the objective to 2030 according to the modification of the EU objective through the approbation of the Green Deal.Base year is 1990 (CO2, CH4, N2O) and 1995 for fluorinated gases (HFCs, PFCs and SF6)",
    region_name: "Thuringia",
  },
  {
    pledge_id: 62,
    pledge_type: 2002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2005,
    pledge_base_level: 86500000,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Reduction of region-wide CO2eq emissions by 20% by 2020 based on 2005 levels.The target takes into account the emissions trend and the scenarios assessed by the Regional Energy Program.The emissions considered are all those within the regional territory except point source emissions included in the EUETS(Emission Trading System of the European Union), plus indirect emissions from regional power consumption.The target applies to the sources in sectors a+c+d+e+f+g defined in Q 3.11 d.",
    region_name: "CONGOPE",
  },
  {
    pledge_id: 63,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Pastaza",
  },
  {
    pledge_id: 64,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 236190000,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The CLCPA sets a long-term target of 85% reduction from 1990.  The act also revises the 1990 baseline to be developed from 20-yr GWP and include imported electricity emissions along with upstream emissions from fossil fuels consumed within the state.  This baseline will be revised in the future (by Jan 1, 2021) to be consistent with this act.  Currently the 1990 emissions reported here are based on 100-yr GWP and do not include upstream fossil fuel emissions.",
    region_name: "Santa Elena",
  },
  {
    pledge_id: 65,
    pledge_type: 6.890203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2011,
    pledge_base_level: 908149370.8,
    pledge_target: 6.89,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The emissions reduction target based on Pergub Number 125/2020 on RAD-GRK 2020-2030, where the Forest and Other Land Use (FOLU) sector prioritized on provincial authority. The GoWK has pledged its emissions target to 60% by 2030 from its BaU baseline as stated on SRAP REDD+, 2017.",
    region_name: "Andalusia",
  },
  {
    pledge_id: 66,
    pledge_type: 10002045,
    pledge_target_year: 2045,
    pledge_baseline_year: 1990,
    pledge_base_level: 76292561,
    pledge_target: 100,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The Climate Change (Scotland) Act 2009 sets a target for net zero emissions of all greenhouse gases by 2045 (5 years ahead of the UK target date of 2050).   Statutory interim targets are set for 2020, 2030 and 2040, for emissions reductions of 56%, 75% and 90% from the 1990-95 baseline.  Legislation also makes provision for annual targets for every year to 2045.  Current annual targets available at: https://www.gov.scot/policies/climate-change/reducing-emissions/.  The greenhouse gases covered by the targets are carbon dioxide, methane and nitrous oxide, for which the baseline is 1990; and hydrofluorocarbons, perfluorocarbons, sulphur hexafluoride, and nitrogen trifluoride, for which the baseline is 1995.  The targets are economy-wide and include emissions and removals from land use change and forestry.  As well as domestic emissions, Scotlandâ€™s share of emissions from international aviation and shipping are included in the targets.",
    region_name: "Balearic Islands",
  },
  {
    pledge_id: 67,
    pledge_type: 7002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 0,
    pledge_target: 70,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Target for 2030: 60-70 % reduction ( action is geared to maximum emission reduction) Taget is fixed in  the bill of an Thuringian Climate Act;",
    region_name: "Balearic Islands",
  },
  {
    pledge_id: 68,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 25634155,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "40% emissions reduction in 2030 and 80% emissions reduction in 2050. The target is aligned with European Union decarbonization pathway to 2050 and the contribution to  2ÂºC Paris Pledge.",
    region_name: "Basque Country",
  },
  {
    pledge_id: 69,
    pledge_type: 2802020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2015,
    pledge_base_level: 3076750,
    pledge_target: 28,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The projection of GHG emission reduction through mitigation scenarios from 2010 to 2020 is estimated to be reduced from 3076.75 Thousand Tons of CO2 eq to 2657.79 Thousand Tons of CO2 eq. The largest percentage of emission reduction contributors was the power generation sector 50.30%, followed by the commercial sector 24.39%, households 21.81%, other sectors 3.08%, and industrial sector 0.42%.",
    region_name: "Basque Country",
  },
  {
    pledge_id: 70,
    pledge_type: 5502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 697681,
    pledge_target: 55,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Cantabria",
  },
  {
    pledge_id: 71,
    pledge_type: 3002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 190619000,
    pledge_target: 30,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "ClimateWorks Australia and The Climate Institute prepared a Technical Report: Queensland can achieve net zero emissions by 2050: How the Sunshine State stands to benefit by taking action while managing the risks of transition. The 130 page, report provides a detailed analysis of the emission reduction opportunities in Queensland by sector: electricity generation; mining and industry; buildings; transport; and land and agriculture. Each sector includes a summary of Business as Usual, the emissions reduction opportunity, cost considerations and the co-benefits and barriers with implementing the opportunities to reach net zero emissions. The report is available at:  https://www.qld.gov.au/__data/assets/pdf_file/0023/136535/executive-summary-qld-net-zero-emissions-2050.pdfThe Queensland Government commissioned Ernst & Young to assess the risks and opportunities to eight key Queensland economic sectors of a transition to a zero net emissions global economy by 2050, which included extensive stakeholder engagement to identify policy options to support the transition. The work was completed in early 2019 and the Executive Summary is available at: https://www.qld.gov.au/__data/assets/pdf_file/0010/101701/ernst-young-qld-zero-net-emissions-future-exec-summary.pdf",
    region_name: "Cantabria",
  },
  {
    pledge_id: 72,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 2005,
    pledge_base_level: 158412376,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The goal is to reduce statewide GHG emissions across all sectors producing emissions to a level at least 15 percent below 2005 levels by 2015, at least 30 percent below 2005 levels by 2025, and at least 80 percent below 2005 levels by 2050. The inventory and targets include the conventional GHGs: carbon dioxide (CO2), nitrous oxide (N2O), methane (CH4), sulfur hexafluoride (SF6), hydrofluorocarbons (HFCs) and perfluorocarbons (PFCs). Emissions estimates are organized by economic sectors: electricity generation, transportation, agriculture, industrial, residential, commercial, and waste. Major sources within each sector are -Electricity Generation: Fuel combustion, emissions from electricity consumption in Minnesota, including electricity imported to meet demandTransportation: Fuel combustion in gasoline and diesel vehicles, aviation, rail, air conditioning leakage, natural gas pipelines Agriculture: Livestock flatulence, animal feedlots and manure management, fertilizer use, crop cultivation, fuel combustion Industrial: Fuel combustion, taconite processing, petroleum refining, magnesium casting, lead recycling, and manufacturing steel, glass, insulating foam, and semiconductors Residential: Fuel combustion (space and water heating, dryers), fertilizer and product use,  carbon storage in housing material, air conditioner and refrigerator leakage Commercial: Fuel combustion, solvent use, medical N2O, includes institutional sources Waste: Waste processing and incineration, methane from landfill gas and wastewater, carbon storage in demolition landfills  Only emissions that occur within the geographical borders of the state are estimated, with the exception of emissions from net imports of electricity into the state to meet Minnesota demand and the combustion of aviation fuel purchased in Minnesota. Long-term storage of carbon in residential structures and demolition and construction landfills is included in statewide GHG emission totals. The carbon storage in forests and forest soils is currently tracked separately from the emissions inventory and will be integrated in the next edition.",
    region_name: "Catalonia",
  },
  {
    pledge_id: 73,
    pledge_type: 5002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 35632000,
    pledge_target: 50,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Reduce net emissions by more than 50% by 2030 from 2005 levels.",
    region_name: "Catalonia",
  },
  {
    pledge_id: 74,
    pledge_type: 8002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 431000000,
    pledge_target: 80,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The State's targets are focused on reducing GHG emissions from industrial and fossil fuel sources.  No specific pathway has been identified at this time to achieve the 2050 target.",
    region_name: "Kymenlaakso",
  },
  {
    pledge_id: 75,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 2017,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Southern Ostrobothnia",
  },
  {
    pledge_id: 76,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Grand Est",
  },
  {
    pledge_id: 77,
    pledge_type: 2002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2010,
    pledge_base_level: 11231,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "todavÃ­a no se tienen informaciÃ³n precisa de los datos solicitados ya que estamos apenas en la propuesta de construcciÃ³n y luego en la implementaciÃ³n",
    region_name: "La RÃ©union",
  },
  {
    pledge_id: 78,
    pledge_type: 37.50203,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 27073000,
    pledge_target: 37.5,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "GHGs covered by the target include CO2, CH4, N2O, SF6, NF3, HFCs and PFCs. This target is inscribed in QuÃ©bec's sustainable mobility policy rather than QuÃ©bec's climate change action plan.",
    region_name: "La RÃ©union",
  },
  {
    pledge_id: 79,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Occitanie",
  },
  {
    pledge_id: 80,
    pledge_type: 3302025,
    pledge_target_year: 2025,
    pledge_baseline_year: 2005,
    pledge_base_level: 121446794,
    pledge_target: 33,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Note: Victoriaâ€™s 2030 emissions reduction target is 28-33% below 2005 levels.",
    region_name: "Scotland",
  },
  {
    pledge_id: 81,
    pledge_type: 0.10203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2011,
    pledge_base_level: 73614729.38,
    pledge_target: 0.1,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The emissions reduction target by promoting the organic fertilizer, integrated agriculture management and low-emissions variety application.",
    region_name: "Scotland",
  },
  {
    pledge_id: 82,
    pledge_type: 3502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2014,
    pledge_base_level: 485790,
    pledge_target: 35,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Cf the actions plan of the Energy transition scheme for New Caledonia in the Residential and tertiary sector.",
    region_name: "Wales",
  },
  {
    pledge_id: 83,
    pledge_type: 2002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2019,
    pledge_base_level: 0,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Technical capacity and knowledge needed to boost committee work",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 84,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "This objective is enshrined into Law 16/2017, of 1 August, on Climate Change (consolidated version in force as of 1st October 2020)",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 85,
    pledge_type: 10002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 56255319.56,
    pledge_target: 100,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The Environment (Wales) Act introduces Wales' first statutory emissions reduction target. The Act originally introduced a 2050 target of at least an 80% reduction in emissions compared to 1990 levels. In March 2021 Senedd Cymru approved a net zero target for 2050. Wales also has interim targets for 2030 and 2040, and a series of 5-year carbon budgets. The first carbon budget ran from 2016 to 2020. Alongside the net zero target, we also updated our interim targets and 2nd and 3rd carbon budgets, as follows:â€¢Carbon Budget 2 (2021-25): 37% average reductionâ€¢Carbon Budget 3 (2026-30): 58% average reduction â€¢2030: 63% reductionâ€¢2040: 89% reductionWe have to set a carbon budget at least five years before the budgetary period begins. The targets and carbon budgets form Walesâ€™s statutory framework. The targets and budgets cover all emissions sources and sinks in Wales. They also include emissions associated with Wales' share of international aviation and shipping emissions. The targets and budgets are set against a Net Welsh Emissions Account which allows international offset credits (Clean Development Mechanism Units) to be credited to the account. However we have set a 0% offset limit against Carbon budget 2.",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 86,
    pledge_type: 1002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2005,
    pledge_base_level: 4084620,
    pledge_target: 10,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 87,
    pledge_type: 3302030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2014,
    pledge_base_level: 0,
    pledge_target: 33,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Extrapolation linear trend based on historical data; 2014: 0,358 kg CO2-Ã¤quiv./Euro-real; 2016: 0,361 kg CO2-Ã¤quiv./Euro-real; 2017: 0,362 kg CO2-Ã¤quiv./Euro-real; 2018: 0,32 kg CO2-Ã¤quiv./Euro-real; 2019: 0,337 kg CO2-Ã¤quiv./Euro-realsecond target: energy-related greenhouse gas emissions with a reduction in emissions-intensity (greenhouse gases related to gross regional product) by 70 to 90% by 2050",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 88,
    pledge_type: 6502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 0.32,
    pledge_target: 65,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In 2030, the state-wide solid waste GHG per capita emissions shall be 65% lower than that of 2005 of 321.8 kg CO2e/inhab. In 2015, this indicator decreased to 186.9 kg CO2e/inhab. In 2030, these emissions shall be reduced even further to 112.6 kg CO2e/inhab.",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 89,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "West Kalimantan",
  },
  {
    pledge_id: 90,
    pledge_type: 1002020,
    pledge_target_year: 2020,
    pledge_baseline_year: 2011,
    pledge_base_level: 0,
    pledge_target: 10,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Short target summary: Reduce the CO2 emissions in the islands territories in IO in enhancing the south/south cooperation and the spread ofgreen projects.Please detail and comment on any progress to reach target: The Regional Council of La Reunion is setting up a Hub R20 Energy in order to diffuse green projects in Indian Oceanin order to develop endogenous low carbon economy",
    region_name: "West Nusa Tenggara",
  },
  {
    pledge_id: 91,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "West Nusa Tenggara",
  },
  {
    pledge_id: 92,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 4.73,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In 2030, the state-wide GDP carbon intensity indicator shall be lower than that of 2005 of 0.13 tonnes CO2e/R$ 1,000. There is, however, no estimation for what this emission should be in 2030.The state-wide GDP carbon intensity of Rio de Janeiro in 2015 reached 0.15 tonnes of CO2e per R$1,000 which is higher than the baseline.Besides, the GNP have increased only 25,6% what reflects in the rising of the GNPâ€™s carbon content.",
    region_name: "Abruzzo",
  },
  {
    pledge_id: 93,
    pledge_type: 6502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 0.07,
    pledge_target: 65,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In 2030, the state-wide sewage GHG per capita emissions shall be 65% lower than that of 2005 of 68.0 kg CO2e/inhab.In 2015, this indicator reached 79.2 kg CO2e/inhab, hiegher than the baseline value. In 2030, these emissions shall be reduced to 23.8 kg CO2e/inhab.",
    region_name: "Lombardy",
  },
  {
    pledge_id: 94,
    pledge_type: 3002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2010,
    pledge_base_level: 0,
    pledge_target: 30,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "In 2030, the state-wide transport GHG emissions shall be 30% lower than that of 2010.Emissions from this source increased 32.3% between 2010 and 2015.",
    region_name: "Lombardy",
  },
  {
    pledge_id: 95,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Lombardy",
  },
  {
    pledge_id: 96,
    pledge_type: 2002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 2400000,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Para 2030, implementar medidas de EE elÃ©ctrica en todo el sector industrial suficientes para lograr una reducciÃ³n del 20% en el consumo de electricidad.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Marche",
  },
  {
    pledge_id: 97,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Piedmont",
  },
  {
    pledge_id: 98,
    pledge_type: 6002035,
    pledge_target_year: 2035,
    pledge_baseline_year: 2015,
    pledge_base_level: 2400000,
    pledge_target: 60,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Para el 2035, se implementarÃ¡n todos los mecanismos necesarios para apoyar la planificaciÃ³n urbana inteligente que cubra al60% de la poblaciÃ³n del estado de QuerÃ©taro. Esto incluye los municipios de Corregidora, El MarquÃ©s, Huimilpan y QuerÃ©taro.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Sardinia",
  },
  {
    pledge_id: 99,
    pledge_type: 2.70203,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 10.4,
    pledge_target: 2.7,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Se llevÃ³ a cabo una evaluaciÃ³n de las metas de reducciÃ³n de emisiones a nivel estatal necesarias para lograr la coherencia con el objetivo de limitar el calentamiento global a 2Â°C. â€¢ Para el aÃ±o 2030, 21% reducciÃ³n de emisiones de GEI por debajo del nivel de emisiones de 2015.â€¢ Para el aÃ±o 2050, 63% reducciÃ³n de emisiones de GEI por debajo del nivel de emisiones de 2015.",
    region_name: "Sardinia",
  },
  {
    pledge_id: 100,
    pledge_type: 2502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 300000,
    pledge_target: 25,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Esta acciÃ³n estÃ¡ diseÃ±ada para reducir las emisiones de gases de efecto invernadero (GEI) (principalmente CO2) del suministro elÃ©ctrico en QuerÃ©taro mediante la construcciÃ³n de nuevos proyectos de energÃ­a solar distribuida (producciÃ³n in situ de energÃ­a renovable) en el sector comercial e institucional del Estado.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Sardinia",
  },
  {
    pledge_id: 101,
    pledge_type: 3802030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2014,
    pledge_base_level: 1765760,
    pledge_target: 38,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "O primeiro inventÃ¡rio de emissÃµes foi realizado em 2014 e o Programa Regional para as AlteraÃ§Ãµes ClimÃ¡ticas foi aprovado no final de 2019, pelo que ainda nÃ£o foi efetuada a anÃ¡lise das emissÃµes face Ã s projeÃ§Ãµes definidas para 2030. Ã‰ expectÃ¡vel que as emissÃµes em 2030 aumentem  41% (2.231.253 tCO2eq) na projeÃ§Ã£o alta e na projeÃ§Ã£o baixa diminuam 38% (1.393.814 tCO2eq), em relaÃ§Ã£o a 2014.",
    region_name: "Sardinia",
  },
  {
    pledge_id: 102,
    pledge_type: 2902030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 316502,
    pledge_target: 29,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Ofrecer un tratamiento a los RSM y aguas residuales recolectadas, fomentar su aprovechamiento para reducir las emisiones fugitivas de los residuos.",
    region_name: "Sardinia",
  },
  {
    pledge_id: 103,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 100000,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Para 2030, se habrÃ¡ evitado un total de 7,850 hectÃ¡reas de deforestaciÃ³n.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Sardinia",
  },
  {
    pledge_id: 104,
    pledge_type: 3302030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 2400000,
    pledge_target: 33,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Esta acciÃ³n estÃ¡ diseÃ±ada para reducir las emisiones de gases de efecto invernadero (GEI) (principalmente CO2) del consumo de combustibles industriales mediante la implementaciÃ³n de tecnologÃ­as de energÃ­as renovables (ER) para satisfacer las necesidades de energÃ­a tÃ©rmica.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Veneto",
  },
  {
    pledge_id: 105,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Turkana",
  },
  {
    pledge_id: 106,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 100000,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "ExpansiÃ³n del Ecosistema Forestal, esta acciÃ³n tiene por objeto aumentar la absorciÃ³n del diÃ³xido de carbono de la atmÃ³sfera mediante iniciativas que establecen nuevos bosques en zonas actualmente no boscosas en Ã¡reas pÃºblicas y/o privadas en el estado.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Chefchaouen",
  },
  {
    pledge_id: 107,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Chefchaouen",
  },
  {
    pledge_id: 108,
    pledge_type: 4002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 1990,
    pledge_base_level: 6182600,
    pledge_target: 40,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "All targets under this chapter (4.2&4.3 emissions reduction, 4.5 energy savings & efficiency, 4.6 renevable energy) are established by the Regional Law 10/2019 on energy transition and climate change. See the complete document in the web link reffered to in section 4.6.",
    region_name: "Campeche",
  },
  {
    pledge_id: 109,
    pledge_type: 2002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 1271175,
    pledge_target: 20,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Desarrollar las tecnologÃ­as necesarias y la concientizaciÃ³n respecto a los hÃ¡bitos de consumo para mejorar la eficiencia energÃ©tica.",
    region_name: "Campeche",
  },
  {
    pledge_id: 110,
    pledge_type: 9.90205,
    pledge_target_year: 2050,
    pledge_baseline_year: 2015,
    pledge_base_level: 10.4,
    pledge_target: 9.9,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Se llevÃ³ a cabo una evaluaciÃ³n de las metas de reducciÃ³n de emisiones a nivel estatal necesarias para lograr la coherencia con el objetivo de limitar el calentamiento global a 2Â°C. â€¢ Para el aÃ±o 2030, 21% reducciÃ³n de emisiones de GEI por debajo del nivel de emisiones de 2015.â€¢ Para el aÃ±o 2050, 63% reducciÃ³n de emisiones de GEI por debajo del nivel de emisiones de 2015.",
    region_name: "Campeche",
  },
  {
    pledge_id: 111,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Campeche",
  },
  {
    pledge_id: 112,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Guanajuato",
  },
  {
    pledge_id: 113,
    pledge_type: 5002030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 10199112,
    pledge_target: 50,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Evitar la deforestaciÃ³n, a forestar, reforestar y mejorar la sostenibilidad del manejo forestal para lograr un nivel de remociones de carbono superior a las emisiones.",
    region_name: "Jalisco",
  },
  {
    pledge_id: 114,
    pledge_type: 9002050,
    pledge_target_year: 2050,
    pledge_baseline_year: 1990,
    pledge_base_level: 6182600,
    pledge_target: 90,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "All targets under this chapter (4.2&4.3 emissions reduction, 4.5 energy savings & efficiency, 4.6 renevable energy) are established by the Regional Law 10/2019 on energy transition and climate change. See the complete document in the web link reffered to in section 4.6.",
    region_name: "Nuevo LeÃ³n",
  },
  {
    pledge_id: 115,
    pledge_type: 1802030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2005,
    pledge_base_level: 937979,
    pledge_target: 18,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Introducir tÃ©cnicas de manejo mÃ¡s sustentables y eficientes en cuanto al uso de los recursos en el sector agropecuario para lograr una reducciÃ³n de las emisiones de GEI.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 116,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Queretaro",
  },
  {
    pledge_id: 117,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 1200000,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Sistemas agroforestales, esta acciÃ³n tiene por objeto disminuir el diÃ³xido de carbono (CO2) de la atmÃ³sfera mediante iniciativas que establezcan sistemas agroforestales para producir cultivos anuales y/o perennes (tambiÃ©n denominados sistemas agrosilvÃ­colas) en zonas que actualmente se cultivan con sistemas agrÃ­colas de monocultivo o en otras zonas degradadas.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 118,
    pledge_type: 2502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 2500000,
    pledge_target: 25,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "EnergÃ­a solar centralizada, esta acciÃ³n estÃ¡ diseÃ±ada para reducir las emisiones de gases de efecto invernadero (GEI) (principalmente CO2) delsuministro elÃ©ctrico en QuerÃ©taro.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 119,
    pledge_type: 5002035,
    pledge_target_year: 2035,
    pledge_baseline_year: 2015,
    pledge_base_level: 2400000,
    pledge_target: 50,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "ElectrificaciÃ³n de vehÃ­culos , esta acciÃ³n estÃ¡ diseÃ±ada para reducir las emisiones de gases de efecto invernadero (GEI) (principalmente CO2) del sector transporte en QuerÃ©taro mediante la electrificaciÃ³n de los vehÃ­culos. La electrificaciÃ³n de los vehÃ­culos reduce las emisiones del tubo de escape al disminuir la proporciÃ³n de la flota de vehÃ­culos que utiliza motores tradicionales de combustiÃ³n interna que queman combustibles fÃ³siles (gasolina y diÃ©sel), es decir, una convergencia entre los sistemas elÃ©ctricos y mecÃ¡nicos. Los trenes de potencia electrificados requieren menos de un tercio de la energÃ­a que requieren los trenes de potencia de motores de combustiÃ³n interna. AdemÃ¡s, las reducciones de GEI de la electrificaciÃ³n de vehÃ­culos aumentan cuando se agrega mÃ¡s energÃ­a renovable a la red elÃ©ctrica de la que se necesita para hacer funcionar los vehÃ­culos elÃ©ctricos. No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 120,
    pledge_type: 2502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 2400000,
    pledge_target: 25,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Esta acciÃ³n estÃ¡ diseÃ±ada para reducir las emisiones de gases de efecto invernadero (GEI) (principalmente CO2) del suministro elÃ©ctrico en QuerÃ©taro mediante la construcciÃ³n de nuevos proyectos de energÃ­a solar distribuida (expansiÃ³n de la producciÃ³n de energÃ­a renovable in situ) en el sector industrial del estado.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 121,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 1200000,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "RegeneraciÃ³n de tierras de pastoreo, esta acciÃ³n tiene por objeto capturar el diÃ³xido de carbono de la atmÃ³sfera, asÃ­ como reducir las emisiones de GEI mediante iniciativas que tienen como objetivo restaurar el carbono del suelo y reducir las pÃ©rdidas de carbono del suelo en los pastizales.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 122,
    pledge_type: 502030,
    pledge_target_year: 2030,
    pledge_baseline_year: 2015,
    pledge_base_level: 2400000,
    pledge_target: 5,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Esta acciÃ³n estÃ¡ diseÃ±ada para reducir las emisiones de gases de efecto invernadero (GEI) (principalmente CO2) del con-sumo de combustibles industriales mediante el desarrollo de una industria de producciÃ³n de biocombustibles en el estado y el uso de estos biocombustibles para compensar el uso de combustibles fÃ³siles.No obstante que el inventario se refiere al aÃ±o base 2015, es relevante mencionar que para la revisiÃ³n y ajuste del inventario de GEI del estado de QuerÃ©taro se considerÃ³ la informaciÃ³n mÃ¡s actualizada posible existente al 2019. Esta informaciÃ³n se integrÃ³ en los cÃ¡lculos y serÃ¡n tomadas como punto de partida para el diseÃ±o de acciones prioritarias especÃ­ficas encaminadas a la reducciÃ³n de emisiones y  el diseÃ±o de acciones de adaptaciÃ³n a los efectos del cambio climÃ¡tico en tres horizontes de tiempo: corto, mediano y largo  plazo.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 123,
    pledge_type: 2045,
    pledge_target_year: 2045,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Queretaro",
  },
  {
    pledge_id: 124,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "We have provisionally set a net zero target for 2050 for the Western Cape and we are currently working on a 2050 Emissions Pathway Exercise which will assist in determing how we will achieve this target.",
    region_name: "Queretaro",
  },
  {
    pledge_id: 125,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Queretaro",
  },
  {
    pledge_id: 126,
    pledge_type: 2040,
    pledge_target_year: 2040,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Queretaro",
  },
  {
    pledge_id: 127,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Queretaro",
  },
  {
    pledge_id: 128,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "As aÃ§Ãµes  aqui  propostas  estabelecem  a  ContribuiÃ§Ã£o  Distritalmente Determinada  (CDD)  com  vistas  a  alcanÃ§ar  um  nÃ­vel  suficiente  de  mitigaÃ§Ã£o  de  gases  de efeito  estufa  no  Distrito  Federal  com  objetivo  de  reduzir  em  20%  as  emissÃµes  de  gases de  efeito  estufa  do  ano  de  referÃªncia  de  2013  atÃ©  o  ano  de  2025,  e  de  37,4%  atÃ©  2030. De  maneira  efetiva  a  reduÃ§Ã£o  de  emissÃµes  alcanÃ§adas  pelas  aÃ§Ãµes  de  mitigaÃ§Ã£o  em 2030  seria  superior  a  4,8  milhÃµes  de  toneladas  de  CO2e,  ou  em  termos  per  capita  uma reduÃ§Ã£o  de  2,38  tCO2e  por  habitante  para  o  ano  de  2030  em  relaÃ§Ã£o  a  de  2013,  uma reduÃ§Ã£o de 51%  da  emissÃ£o per  capita.",
    region_name: "Quintana Roo",
  },
  {
    pledge_id: 129,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Fossil fuel free 2030 - the use of fossil fuels has ceased in 2030",
    region_name: "Quintana Roo",
  },
  {
    pledge_id: 130,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Sonora",
  },
  {
    pledge_id: 131,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "State of Mexico",
  },
  {
    pledge_id: 132,
    pledge_type: 2060,
    pledge_target_year: 2060,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Tabasco",
  },
  {
    pledge_id: 133,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Tabasco",
  },
  {
    pledge_id: 134,
    pledge_type: 2040,
    pledge_target_year: 2040,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Tabasco",
  },
  {
    pledge_id: 135,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Tabasco",
  },
  {
    pledge_id: 136,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "The GoWK has issued the Governorâ€™s Decree Number 1215/2020 on Emissions Reduction Target and Emissions Allocation from Deforestation and Forest Degradation 2020 â€“ 2030",
    region_name: "Veracruz",
  },
  {
    pledge_id: 137,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "YucatÃ¡n",
  },
  {
    pledge_id: 138,
    pledge_type: 2020,
    pledge_target_year: 2020,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "YucatÃ¡n",
  },
  {
    pledge_id: 139,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "YucatÃ¡n",
  },
  {
    pledge_id: 140,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Objetivo de emissÃµes liquidas zero atÃ© 2050, abrangendo todos os setores econÃ´micos.",
    region_name: "YucatÃ¡n",
  },
  {
    pledge_id: 141,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Las metas del Estado de QuerÃ©taro es reducir emisiones netas de GEI para 2030 y 2050",
    region_name: "YucatÃ¡n",
  },
  {
    pledge_id: 142,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "Base year remain unchanged (2005); however base year emissions have changed due to National Inventory Report updates.",
    region_name: "YucatÃ¡n",
  },
  {
    pledge_id: 143,
    pledge_type: 2025,
    pledge_target_year: 2025,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "350 Ha de conservaciÃ³n y 110 ha en restauraciÃ³n anualmente como parte del compromiso estricto del GADPPz, con sus propios recursos que se incrementarÃ¡ dependiendo de los recursos econÃ³micos que se obtengan para la implementaciÃ³n del PdIPPz",
    region_name: "New Caledonia",
  },
  {
    pledge_id: 144,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "New Caledonia",
  },
  {
    pledge_id: 145,
    pledge_type: 2030,
    pledge_target_year: 2030,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "New Caledonia",
  },
  {
    pledge_id: 146,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details:
      "State-wide goal to achieve net zero emissions by 2050",
    region_name: "Cross River State",
  },
  {
    pledge_id: 147,
    pledge_type: 2045,
    pledge_target_year: 2045,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "Net zero emissions by 2045.",
    region_name: "Wellington Region",
  },
  {
    pledge_id: 148,
    pledge_type: 2050,
    pledge_target_year: 2050,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Piura",
  },
  {
    pledge_id: 149,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "San MartÃ­n",
  },
  {
    pledge_id: 150,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Lesser Poland Voivodeship",
  },
  {
    pledge_id: 151,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Opole Voivodeship",
  },
  {
    pledge_id: 152,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Azores",
  },
  {
    pledge_id: 153,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Madeira",
  },
  {
    pledge_id: 154,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Madeira",
  },
  {
    pledge_id: 155,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Madeira",
  },
  {
    pledge_id: 156,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Gossas",
  },
  {
    pledge_id: 157,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Saint Louis",
  },
  {
    pledge_id: 158,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "PreÅ¡ovskÃ½ kraj",
  },
  {
    pledge_id: 159,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "JÃ¤mtland",
  },
  {
    pledge_id: 160,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Kronoberg",
  },
  {
    pledge_id: 161,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Kronoberg",
  },
  {
    pledge_id: 162,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "California",
  },
  {
    pledge_id: 163,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "California",
  },
  {
    pledge_id: 164,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Connecticut",
  },
  {
    pledge_id: 165,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Connecticut",
  },
  {
    pledge_id: 166,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Connecticut",
  },
  {
    pledge_id: 167,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Minnesota",
  },
  {
    pledge_id: 168,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "New York State",
  },
  {
    pledge_id: 169,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "New York State",
  },
  {
    pledge_id: 170,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Oregon",
  },
  {
    pledge_id: 171,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Oregon",
  },
  {
    pledge_id: 172,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Virginia",
  },
  {
    pledge_id: 173,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Washington State",
  },
  {
    pledge_id: 174,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Washington State",
  },
  {
    pledge_id: 175,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Washington State",
  },
  {
    pledge_id: 176,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Washington State",
  },
  {
    pledge_id: 177,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "KwaZulu-Natal",
  },
  {
    pledge_id: 178,
    pledge_type: 0,
    pledge_target_year: 0,
    pledge_baseline_year: 0,
    pledge_base_level: 0,
    pledge_target: 0,
    conditionality: null,
    pledge_standard: null,
    pledge_plan_details: "",
    region_name: "Western Cape",
  },
];
