name: 'Chromatic Deployment'

on:
    workflow_dispatch:
    push:
      paths:
        - ui/.storybook/**
        - ui/src/stories/**
      branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}