name: Run OpenClimate importer

on:
  push:
    paths:
      - harmonize/data/processed/**
      - k8s/openclimate-import-zip-job.yml
    branches: [ "develop" ]

jobs:

  runImportJobOnEKS:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EKS_DEV_USER }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EKS_DEV_USER }}
        EKS_DEV_NAME: ${{ secrets.EKS_DEV_NAME }}
      steps:

      - uses: actions/checkout@v2.3.4

      - name: Creating kubeconfig file
        run: aws eks update-kubeconfig --name ${{secrets.EKS_DEV_NAME}} --region us-east-1

      - name: Testing connection to EKS
        run: kubectl get pods -n default

      - name: Creating import from zip job on EKS
        run: |
          kubectl create -f k8s/openclimate-import-zip-job.yml -n default