name: Push OpenClimate importer to ECR

on:
  push:
    paths:
      - import/**
    branches: [ "develop" ]
  pull_request:
    paths:
      - import/**
    branches: [ "develop" ]

jobs:
  pushToECR:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.3.4

    - name: Logging in to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation

    - name: Pushing OC-API to ECR
      env:
        VERSION: ${{ github.sha }}
        IMAGE: public.ecr.aws/openearthfoundation/openclimate-import

      run: |
        docker build -t $IMAGE:$VERSION import
        docker tag $IMAGE:$VERSION $IMAGE:latest
        docker push $IMAGE:$VERSION
        docker push $IMAGE:latest

  runImportJobOnEKS:
      needs: pushToECR
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EKS_DEV_USER }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EKS_DEV_USER }}
        EKS_DEV_NAME: ${{ secrets.EKS_DEV_NAME }}
      steps:

      - uses: actions/checkout@v2.3.4

      - name: Creating kubeconfig file
        run: aws eks update-kubeconfig --name ${{secrets.EKS_DEV_NAME}} --region us-east-1

      - name: Testing connection to EKS
        run: kubectl get pods -n default

      - name: Creating import from zip job on EKS
        run: |
          kubectl create -f k8s/openclimate-import-zip-job.yml -n default