name: Push UI main to ECR stable

on:
  workflow_dispatch:
  push:
    paths:
      - ui/**
    branches: [ "main" ]

jobs:

  pushToECR:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.3.4

    - name: Logging in to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation

    - name: Pushing OC-UI to ECR
      env:
        SHA: ${{ github.sha }}
        IMAGE: public.ecr.aws/openearthfoundation/openclimate-ui

      run: |
        export VERSION=`node -pe "require('./ui/package.json').version"`
        export MAJOR=${VERSION%.*.*}
        export MINOR=${VERSION%.*}
        echo Version: ${VERSION} Major: ${MAJOR} Minor: ${MINOR}
        docker build -t $IMAGE:$SHA ui
        docker tag $IMAGE:$SHA $IMAGE:$VERSION
        docker tag $IMAGE:$SHA $IMAGE:$MAJOR
        docker tag $IMAGE:$SHA $IMAGE:$MINOR
        docker tag $IMAGE:$SHA $IMAGE:stable
        docker push $IMAGE:$SHA
        docker push $IMAGE:$VERSION
        docker push $IMAGE:$MAJOR
        docker push $IMAGE:$MINOR
        docker push $IMAGE:stable
