name: Push OpenClimate-to-ElasticSearch indexer develop to ECR latest

on:
  workflow_dispatch:
  push:
    paths:
      - openclimate-to-elasticsearch/**
    branches: [ "develop" ]

jobs:
  pushToECR:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Logging in to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation

    - name: Pushing OC2ES to ECR
      env:
        VERSION: ${{ github.sha }}
        IMAGE: public.ecr.aws/openearthfoundation/openclimate-to-elasticsearch

      run: |
        docker build -t $IMAGE:$VERSION openclimate-to-elasticsearch
        docker tag $IMAGE:$VERSION $IMAGE:latest
        docker push $IMAGE:$VERSION
        docker push $IMAGE:latest
